/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jlarhdcxatsutkmwqqvh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYXJoZGN4YXRzdXRrbXdxcXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4NTc5NzEsImV4cCI6MjA5ODQzMzk3MX0.jKaD04TT83rbeizyvF0cBcMr-9P1gzVpK28hTS6IaYg"
